- hosts: all
  roles:
    - common
    - { role: bgp, when: "bgpd_enable_state['results'][0]['item'] == true" }


    # - rsyslog
  # tasks:
  #   - name: Is Flexswitch Ready?
  #     uri:
  #       url: "https://localhost:443/public/v1/state/systemstatus"
  #       method: GET
  #       status_code: 200
  #       user: "{{api_user}}"
  #       password: "{{api_password}}"
  #       force_basic_auth: yes
  #       validate_certs: no
  #       return_content: yes
  #     register: post_result
  #     until: post_result.json.Object.Ready == true
  #     retries: 10

    # - name: Set timezone
    #   # when: ansible_hostname == "localhost" or
    #   #   ansible_hostname == "(none)"
    #   uri:
    #     # body: "{'Hostname':'localhost-{{ansible_default_ipv4.address.split('.')[3]}}'}"
    #     body: '{"Timezone":"America/New_York"}'
    #     method: PATCH
    #     url: https://localhost:443/public/v1/config/SystemParam
    #     body_format: json
    #     user: "{{api_user}}"
    #     password: "{{api_password}}"
    #     force_basic_auth: yes
    #     validate_certs: no
    #     return_content: yes