- name: Get FlexSwitch SystemState
  uri:
    url: "https://localhost:443/public/v1/state/systemstatus"
    method: GET
    status_code: 200
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  register: json_response
  until: json_response.json.Object.Ready == true
  retries: 10
  tags: 
    - systemstatus

- set_fact:
    flexswitch_system_state: "{{ json_response.json.Object.Ready }}"
    lacpd_enable_state: "{{ json_response.content | from_json | json_query(lacpd_status_query) }}"
    ndpd_enable_state: "{{ json_response.content | from_json | json_query(ndpd_status_query) }}"
    ribd_enable_state: "{{ json_response.content | from_json | json_query(ribd_status_query) }}"
    fMgrd_enable_state: "{{ json_response.content | from_json | json_query(fMgrd_status_query) }}"
    stpd_enable_state: "{{ json_response.content | from_json | json_query(stpd_status_query) }}"
    vxland_enable_state: "{{ json_response.content | from_json | json_query(vxland_status_query) }}"
    confd_enable_state: "{{ json_response.content | from_json | json_query(confd_status_query) }}"
    vrrpd_enable_state: "{{ json_response.content | from_json | json_query(vrrpd_status_query) }}"
    ospfv2d_enable_state: "{{ json_response.content | from_json | json_query(ospfv2d_status_query) }}"
    asicd_enable_state: "{{ json_response.content | from_json | json_query(asicd_status_query) }}"
    platformd_enable_state: "{{ json_response.content | from_json | json_query(platformd_status_query) }}"
    bfdd_enable_state: "{{ json_response.content | from_json | json_query(bfdd_status_query) }}"
    arpd_enable_state: "{{ json_response.content | from_json | json_query(arpd_status_query) }}"
    sysmgmtd_enable_state: "{{ json_response.content | from_json | json_query(sysmgmtd_status_query) }}"
    notifierd_enable_state: "{{ json_response.content | from_json | json_query(notifierd_status_query) }}"
    lldpd_enable_state: "{{ json_response.content | from_json | json_query(lldpd_status_query) }}"
    statsd_enable_state: "{{ json_response.content | from_json | json_query(statsd_status_query) }}"
    dhcprelayd_enable_state: "{{ json_response.content | from_json | json_query(dhcprelayd_status_query) }}"
    dhcpd_enable_state: "{{ json_response.content | from_json | json_query(dhcpd_status_query) }}"
    bgpd_enable_state: "{{ json_response.content | from_json | json_query(bgpd_status_query) }}"


- name: Set hostname
  when: flexswitch_system_state
  uri:
    body:
      Hostname: "{{ hostname }}"
    method: PATCH
    url: https://localhost:443/public/v1/config/SystemParam
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  tags: 
    - hostname

- name: Set timezone
  uri:
    body:
      Timezone: "America/New_York"
    method: PATCH
    url: https://localhost:443/public/v1/config/SystemParam
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  tags: 
    - timezone

- name: Set NTP server
  when: ntp_server is defined
  uri:
    body:
      IpAddr: "{{ ntp_server }}"
    method: POST
    url: https://localhost:443/public/v1/config/NtpServer
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    status_code: 201
  tags: 
    - ntpserver

- set_fact:
    Banner: "Ansible-configured banner\n"
    when: Banner is undefined

- set_fact:
    MOTD: "Ansible-configured MOTD\n"
    when: MOTD is undefined


- name: Set login banners
  uri:
    body:
      Banner: "{{ Banner }}"
      MOTD: "{{ MOTD }}"
    method: PATCH
    url: https://localhost:443/public/v1/config/SystemSsh
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  tags:
    - loginbanner-and-motd

- name: Enable LLDP
  when: lldpd_enable_state == [True]
  uri:
    body:
      Enable: true
    method: PATCH
    url: https://localhost:443/public/v1/config/LLDPGlobal
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  tags: 
    - lldpglobal

- name: Setup SYSLOG forwarding to {{syslog_aggregator}}
  uri:
    body: 
      ServerIpAddr: "{{ syslog_aggregator }}"
    method: POST
    url: https://localhost:443/public/v1/config/SyslogCollector
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    status_code: 200, 201
  tags: 
    - syslogcollector

- name: Create logical interface 0
  uri:
    body: 
      Name: "lo0"
      Type: "Loopback"
      Description: "Ansible-created lo0"
    method: POST
    url: https://localhost:443/public/v1/config/LogicalIntf
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    status_code: 200, 201
  tags:
    - createlo0

- name: Assign an IP ({{lo0_address}}) to lo0
  uri:
    body: 
      IntfRef: "lo0"
      IpAddr: "{{ lo0_address }}"
    method: POST
    url: https://localhost:443/public/v1/config/IPv4Intf
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    status_code: 200, 201
  tags:
    - ip_lo0
