- name: Set BGP Config
  uri:
    body: 
      ASNum: "{{ ASNum }}"
      RouterID: "{{ RouterID }}"
      Disabled: false
    method: PATCH
    url: https://localhost:443/public/v1/config/BGPGlobal
    body_format: json
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    tags: 
      - bgp_enable