lacpd_status_query: "Object.FlexDaemons[?Name=='lacpd'].Enable"
ndpd_status_query: "Object.FlexDaemons[?Name=='ndpd'].Enable"
ribd_status_query: "Object.FlexDaemons[?Name=='ribd'].Enable"
fMgrd_status_query: "Object.FlexDaemons[?Name=='fMgrd'].Enable"
stpd_status_query: "Object.FlexDaemons[?Name=='stpd'].Enable"
vxland_status_query: "Object.FlexDaemons[?Name=='vxland'].Enable"
confd_status_query: "Object.FlexDaemons[?Name=='confd'].Enable"
vrrpd_status_query: "Object.FlexDaemons[?Name=='vrrpd'].Enable"
ospfv2d_status_query: "Object.FlexDaemons[?Name=='ospfv2d'].Enable"
asicd_status_query: "Object.FlexDaemons[?Name=='asicd'].Enable"
platformd_status_query: "Object.FlexDaemons[?Name=='platformd'].Enable"
bfdd_status_query: "Object.FlexDaemons[?Name=='bfdd'].Enable"
arpd_status_query: "Object.FlexDaemons[?Name=='arpd'].Enable"
sysmgmtd_status_query: "Object.FlexDaemons[?Name=='sysmgmtd'].Enable"
notifierd_status_query: "Object.FlexDaemons[?Name=='notifierd'].Enable"
lldpd_status_query: "Object.FlexDaemons[?Name=='lldpd'].Enable"
statsd_status_query: "Object.FlexDaemons[?Name=='statsd'].Enable"
dhcprelayd_status_query: "Object.FlexDaemons[?Name=='dhcprelayd'].Enable"
dhcpd_status_query: "Object.FlexDaemons[?Name=='dhcpd'].Enable"
bgpd_status_query: "Object.FlexDaemons[?Name=='bgpd'].Enable"
